language: node_js
node_js:
- '5.3'
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: liftit.alexjpaz.com
  cache_control: "max-age=3600"
  skip_cleanup: true
  local-dir: web/public
  acl: public_read
  on:
    branch: web-client
    repo: alexjpaz/liftit
