sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_8e5a0429f0a8_key -iv $encrypted_8e5a0429f0a8_iv
  -in liftit-9aaa156b481d.json.enc -out liftit-9aaa156b481d.json -d
script:
- ./tasks build
deploy:
- provider: gae
  config: datastore/app.yaml
  keyfile: liftit-9aaa156b481d.json
  default: true
  project: liftit-1138
  skip_cleanup: true
